# fly.toml app configuration file generated for natality-stats on 2026-04-10T16:58:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'natality-stats'
primary_region = 'ord'
kill_signal = 'SIGINT'
kill_timeout = 5
swap_size_mb = 512

[experimental]
auto_rollback = true

[[services]]
  internal_port = 8080
  processes = [ "app" ]
  protocol = "tcp"
  script_checks = [ ]

  [services.concurrency]
  hard_limit = 100
  soft_limit = 80
  type = "requests"

  [[services.ports]]
  handlers = [ "http" ]
  port = 80
  force_https = true

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443

[[vm]]
  memory = '3gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048